In [1]:
from numpy import *

In [ ]:
# N = 2 case

In [4]:
import numpy as np
np.set_printoptions(suppress=True)


ep = 0.1

coeff = round(1/(2*sqrt(2)+ep),3)

print("Our matrix")
print("    P      a1      a2      b1      b2      s      t      Value")
A1 = array([[1,-10,10,-coeff,coeff,0,0,0],
           [0,-10,10,-coeff,coeff,1,0,-ep**2],
           [0,coeff,-coeff,10,-10,0,1,-ep**2],
           [0,1,-1,1,-1,0,0,0]])

print(A1)

print()
print("Look top row, find smallest value and its column. Then:")
print("Perform division on rightmost column by that column, excluding top row.")
print("Smallest number becomes your pivot")
print()

L1 = [A1[1,7]/A1[1,1],A1[2,7]/A1[2,1],A1[3,7]/A1[3,1]]


print(L1)
print()
print("Pivot is at A[2,1]")
print()

A2 = A1.copy()

A2[0] = A1[0] - (A1[0,1]/A1[2,1])*A1[2]
A2[1] = A1[1] - (A1[1,1]/A1[2,1])*A1[2]
A2[2] = A1[2]/A1[2,1]
A2[3] = A1[3] - (A1[3,1]/A1[2,1])*A1[2]

print("Iteration 1")
print(A2.round(3))

print()
print()
print("Look top row, find smallest value and its column. Then:")
print("Perform division on rightmost column by that column, excluding top row.")
print("Smallest number becomes your pivot")
print()

L2 = [A2[1,7]/A2[1,4],A2[2,7]/A2[2,4],A2[3,7]/A2[3,4]]

print(L2)
print()
print("Pivot is at A[2,4]")
print()

A3 = A2.copy()

A3[0] = A2[0] - (A2[0,4]/A2[2,4])*A2[2]
A3[1] = A2[1] - (A2[1,4]/A2[2,4])*A2[2]
A3[2] = A2[2]/A2[2,4]
A3[3] = A2[3] - (A2[3,4]/A2[2,4])*A2[2]

print("Iteration 2")
print(A3.round(5))

print()
print()
print("Look top row, find smallest value and its column. Then:")
print("Perform division on rightmost column by that column, excluding top row.")
print("Smallest number becomes your pivot")
print()

L3 = [A3[1,7]/A3[1,1],A3[2,7]/A3[2,1],A3[3,7]/A3[3,1]]

print(L3)
print()
print("Pivot is at A[2,1]")
print()

A4 = A3.copy()

A4[0] = A3[0] - (A3[0,1]/A3[2,1])*A3[2]
A4[1] = A3[1] - (A3[1,1]/A3[2,1])*A3[2]
A4[2] = A3[2]/A3[2,1]
A4[3] = A3[3] - (A3[3,1]/A3[2,1])*A3[2]

print("Iteration 3")
print(A4.round(3))


Our matrix
    P      a1      a2      b1      b2      s      t      Value
[[  1.    -10.     10.     -0.341   0.341   0.      0.      0.   ]
 [  0.    -10.     10.     -0.341   0.341   1.      0.     -0.01 ]
 [  0.      0.341  -0.341  10.    -10.      0.      1.     -0.01 ]
 [  0.      1.     -1.      1.     -1.      0.      0.      0.   ]]

Look top row, find smallest value and its column. Then:
Perform division on rightmost column by that column, excluding top row.
Smallest number becomes your pivot

[0.0010000000000000002, -0.029325513196480944, 0.0]

Pivot is at A[2,1]

Iteration 1
[[   1.       0.       0.     292.914 -292.914    0.      29.326   -0.293]
 [   0.       0.       0.     292.914 -292.914    1.      29.326   -0.303]
 [   0.       1.      -1.      29.326  -29.326    0.       2.933   -0.029]
 [   0.       0.      -0.     -28.326   28.326    0.      -2.933    0.029]]


Look top row, find smallest value and its column. Then:
Perform division on rightmost column by that col

In [14]:
import numpy as np
np.set_printoptions(suppress=True)


ep = 0.1

coeff = round(1/(2*sqrt(2)+ep),3)

print("Our matrix")
print("    P      a1      a2      b1      b2      s      t      Value")
A1 = array([[1,-10,10,-coeff,coeff,0,0,0],
           [0,-10,10,-coeff,coeff,1,0,-ep**2],
           [0,coeff,-coeff,10,-10,0,1,-ep**2],
           [0,1,-1,1,-1,0,0,0],
           [0,1,1,0,0,0,0,1],
           [0,0,0,1,1,0,0,1]])

print(A1)

print()
print("Look top row, find smallest value and its column. Then:")
print("Perform division on rightmost column by that column, excluding top row.")
print("Smallest number becomes your pivot")
print()

L1 = [A1[1,7]/A1[1,1],A1[2,7]/A1[2,1],A1[3,7]/A1[3,1]]


print(L1)
print()
print("Pivot is at A[2,1]")
print()

A2 = A1.copy()

A2[0] = A1[0] - (A1[0,1]/A1[2,1])*A1[2]
A2[1] = A1[1] - (A1[1,1]/A1[2,1])*A1[2]
A2[2] = A1[2]/A1[2,1]
A2[3] = A1[3] - (A1[3,1]/A1[2,1])*A1[2]
A2[4] = A1[4] - (A1[4,1]/A1[2,1])*A1[2]
A2[5] = A1[5] - (A1[5,1]/A1[2,1])*A1[2]


print("Iteration 1")
print(A2.round(3))

print()
print()
print("Look top row, find smallest value and its column. Then:")
print("Perform division on rightmost column by that column, excluding top row.")
print("Smallest number becomes your pivot")
print()

L2 = [A2[1,7]/A2[1,4],A2[2,7]/A2[2,4],A2[3,7]/A2[3,4],A2[4,7]/A2[4,4],A2[5,7]/A2[5,4]]

print(L2)
print()
print("Pivot is at A[2,4]")
print()

A3 = A2.copy()

A3[0] = A2[0] - (A2[0,4]/A2[2,4])*A2[2]
A3[1] = A2[1] - (A2[1,4]/A2[2,4])*A2[2]
A3[2] = A2[2]/A2[2,4]
A3[3] = A2[3] - (A2[3,4]/A2[2,4])*A2[2]
A3[4] = A2[4] - (A2[4,4]/A2[2,4])*A2[2]
A3[5] = A2[5] - (A2[5,4]/A2[2,4])*A2[2]


print("Iteration 2")
print(A3.round(5))

print()
print()
print("Look top row, find smallest value and its column. Then:")
print("Perform division on rightmost column by that column, excluding top row.")
print("Smallest number becomes your pivot")
print()

L3 = [A3[1,7]/A3[1,1],A3[2,7]/A3[2,1],A3[3,7]/A3[3,1],A3[4,7]/A3[4,1],A3[5,7]/A3[5,1]]

print(L3)
print()
print("Pivot is at A[2,1]")
print()

A4 = A3.copy()

A4[0] = A3[0] - (A3[0,1]/A3[2,1])*A3[2]
A4[1] = A3[1] - (A3[1,1]/A3[2,1])*A3[2]
A4[2] = A3[2]/A3[2,1]
A4[3] = A3[3] - (A3[3,1]/A3[2,1])*A3[2]
A4[4] = A3[4] - (A3[4,1]/A3[2,1])*A3[2]
A4[5] = A3[5] - (A3[5,1]/A3[2,1])*A3[2]


print("Iteration 3")
print(A4.round(3))


Our matrix
    P      a1      a2      b1      b2      s      t      Value
[[  1.    -10.     10.     -0.341   0.341   0.      0.      0.   ]
 [  0.    -10.     10.     -0.341   0.341   1.      0.     -0.01 ]
 [  0.      0.341  -0.341  10.    -10.      0.      1.     -0.01 ]
 [  0.      1.     -1.      1.     -1.      0.      0.      0.   ]
 [  0.      1.      1.      0.      0.      0.      0.      1.   ]
 [  0.      0.      0.      1.      1.      0.      0.      1.   ]]

Look top row, find smallest value and its column. Then:
Perform division on rightmost column by that column, excluding top row.
Smallest number becomes your pivot

[0.0010000000000000002, -0.029325513196480944, 0.0]

Pivot is at A[2,1]

Iteration 1
[[   1.       0.       0.     292.914 -292.914    0.      29.326   -0.293]
 [   0.       0.       0.     292.914 -292.914    1.      29.326   -0.303]
 [   0.       1.      -1.      29.326  -29.326    0.       2.933   -0.029]
 [   0.       0.      -0.     -28.326   28.326  